---
title: "Sepsis HCRU"
author: "Artis Luguzis"
date: 
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, echo = FALSE, include = FALSE}
rm(list = ls())
gc()
```

```{r libs}
library(tidyverse)
library(gtsummary)
library(readxl)
library(survival)
library(ggsurvfit)

source("src/01_utilities/themes.R")
```

```{r formats}
desc_stats <- c(
      # "{N_nonmiss}",
      # "{mean} ({sd})",
      "{median} ({p25}, {p75})"#,
      # "{p10}, {p90}",
      # "{min} - {max}"
    )
```

```{r data}
# incidence un mirstība
load(file = "data/proc/sepsis_counts.RData")
load(file = "data/proc/sepsis_hosp_mirusie_counts.RData")


# kohorta
load(file = "data/proc/hosp_cohort_matched_datasets.RData")
load(file = "data/proc/match_objects.RData")

# HCRU
load("data/proc/clean_mirusie_visi.RData") # mirušie
load("data/proc/clean_komp_med_stac.RData") # kompensējamie medikamenti
load("data/proc/clean_ambul_stac.RData") # ambulatorās epizodes
stac <- readRDS(file = "data/proc/clean_stac.rds") # hospitalizācijas

# specialistu kodi
spec_codes <- read_xlsx("taskfiles/raw/AM_specialitasu_klasifikators_LP_JB.xlsx") %>% 
  janitor::clean_names() %>% 
  # glimpse()
  filter(remove == 0) %>% 
  select(-biezums_gada_2018, -lp, -remove) %>% 
  pivot_longer(laboratory_diagnostics:rehabilitation, names_to = "tips", values_to = "ind") %>% 
  # group_by(specialitates_kods) %>% 
  # summarise(n = sum(ind, na.rm = TRUE)) %>% 
  drop_na() %>%
  # count(n) %>% 
  select(spec_kods = specialitates_kods, tips)

# ssk-10 nosaukumi
ssk10_names <- read_xlsx("taskfiles/raw/ssk10_sekciju_nosaukumi.xlsx")
```

```{r data-proc}
# matched_datasets[[i]] %>% 
#   mutate(diag = substr(diag1, 1, 1)) %>% 
#   count(diag)

# pārveido datumus
komp_med <- komp_med %>% 
  mutate(datums = lubridate::as_date(datums))

ambul <- ambul %>% 
  mutate(across(contains("_datums"), ~lubridate::as_date(.)))

stac <- stac %>% 
  mutate(across(contains("date"), ~lubridate::as_date(.)))

# pievieno miršanas datumu
cohort_inputs <- list()

for (i in 1:4){ #i <- 1
  
  cohort_matched <- matched_datasets[[i]] %>% 
    left_join(mirusie %>% select(pid, nave_date = datums))

  # cik ir mirušo
  # cohort_matched %>% count(!is.na(nave_date))

  # pārbauda, ka nāve visiem pēc izrakstīšanās
  # cohort_matched %>%
  #   count(nave_date > date2)

  # atstāj tikai tos, kas dzīvi izrakstoties
  cohort_matched <- cohort_matched %>% 
    filter(nave_date > date2 | is.na(nave_date))

  # nosaka novēroto datumu (max 365 dienas pēc izrakstīšanas, neieskaitot)
  cohort_matched <- cohort_matched %>% 
    mutate(obs_date = pmin(date2 + 365, nave_date, na.rm = TRUE)) %>% 
    mutate(
      cens = case_when(
        is.na(nave_date) ~ 0,
        obs_date == nave_date ~ 1,
        TRUE ~ 0
      )
    ) %>% 
    mutate(time = as.integer(obs_date - date2))

  # cohort_matched$time %>% summary()
  # hist(cohort_matched$time)

  ## Medikamenti

  # atstāj tikai receptes, kas ir starp izrakstīšanos (ieskaitot un maks beigām)
  drugs <- komp_med %>% 
    filter(pid %in% cohort_matched$pid) %>%
    left_join(cohort_matched %>% select(pid, izrakst_date = date2, obs_date), by = "pid") %>%
    filter(datums > izrakst_date & datums <= obs_date) %>% 
    mutate(across(contains("summa"), ~as.numeric(gsub(",", ".", .)))) %>% 
    mutate(across(contains("lidzmaksajums"), ~as.numeric(gsub(",", ".", .))))

  # check
  # sum(unique(drugs$pid) %in% cohort_matched$pid)
  # length(unique(drugs$pid))

  ## Ambulatorie
  visits <- ambul %>% 
    filter(pid %in% cohort_matched$pid) %>%
    left_join(cohort_matched %>% select(pid, izrakst_date = date2, obs_date), by = "pid") %>%
    filter(sakuma_datums > izrakst_date & sakuma_datums <= obs_date) %>% 
    rename(spec_kods = ap_specialitate)

  # pievieno speciālista tipu
  visits <- visits %>% 
    left_join(spec_codes) %>% 
    drop_na(tips)

  ## Hospitalizācijas
  hosp <- stac %>% 
    filter(pid %in% cohort_matched$pid) %>%
    left_join(cohort_matched %>% select(pid, izrakst_date = date2, obs_date), by = "pid") %>%
    mutate(date1 = lubridate::ymd(date1)) %>% 
    mutate(date2 = lubridate::ymd(date2)) %>% 
    filter(date1 > izrakst_date & date1 <= obs_date) %>% 
    mutate(hosp_ilgums = as.integer(date2 - date1))
  
  max_lookback <- bind_rows(
    ambul %>% filter(pid %in% cohort_matched$pid) %>% select(pid, date = sakuma_datums) %>% mutate(date = as.character(date)),
    stac %>% filter(pid %in% cohort_matched$pid) %>% select(pid, date = date1) %>% mutate(date = as.character(date)),
    komp_med %>% filter(pid %in% cohort_matched$pid) %>% select(pid, date = datums) %>% mutate(date = as.character(date))
  ) %>% 
    mutate(date = lubridate::ymd(date)) %>% 
    arrange(date) %>% 
    distinct(pid, .keep_all = TRUE) %>% 
    rename(min_date = date)

  cohort_matched <- cohort_matched %>% 
    mutate(nave_365 = ifelse(cens == 1, TRUE, FALSE)) %>% 
    mutate(nave_overall = ifelse(!is.na(nave_date), TRUE, FALSE)) %>% 
    mutate(hosp_ilgums = as.integer(date2 - date1)) %>% 
    mutate(across(mi:aids, ~{ifelse(. == "1", TRUE, FALSE)})) %>% 
    left_join(max_lookback, by = "pid") %>% 
    mutate(lookback_time = as.integer(date1 - min_date)) %>% 
    select(pid, tiesie, netiesie, org_trauc, nave_365, nave_overall, diag1, fup_time = time, lookback_time, hosp_ilgums, vecums,
           dzimums, mi:aids, charlson, hosp_gads, cohort) %>% 
    mutate(diag = substr(diag1, 1, 1)) %>% 
    mutate(diag_tmp = substr(diag1, 1, 2)) %>% 
    mutate(
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[1], diag_tmp), ssk10_names$nodala[1], diag_tmp),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[2], diag_tmp_new), ssk10_names$nodala[2], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[3], diag_tmp_new), ssk10_names$nodala[3], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[4], diag_tmp_new), ssk10_names$nodala[4], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[5], diag_tmp_new), ssk10_names$nodala[5], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[6], diag_tmp_new), ssk10_names$nodala[6], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[7], diag_tmp_new), ssk10_names$nodala[7], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[8], diag_tmp_new), ssk10_names$nodala[8], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[9], diag_tmp_new), ssk10_names$nodala[9], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[10], diag_tmp_new), ssk10_names$nodala[10], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[11], diag_tmp_new), ssk10_names$nodala[11], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[12], diag_tmp_new), ssk10_names$nodala[12], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[13], diag_tmp_new), ssk10_names$nodala[13], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[14], diag_tmp_new), ssk10_names$nodala[14], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[15], diag_tmp_new), ssk10_names$nodala[15], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[16], diag_tmp_new), ssk10_names$nodala[16], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[17], diag_tmp_new), ssk10_names$nodala[17], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[18], diag_tmp_new), ssk10_names$nodala[18], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[19], diag_tmp_new), ssk10_names$nodala[19], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[20], diag_tmp_new), ssk10_names$nodala[20], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[21], diag_tmp_new), ssk10_names$nodala[21], diag_tmp_new),
    diag_tmp_new = ifelse(grepl(ssk10_names$regex_range[22], diag_tmp_new), ssk10_names$nodala[22], diag_tmp_new)
  ) %>% 
    select(-diag1, -diag_tmp)
  
  cohort_inputs[[i]] <- list(
    cohort_matched = cohort_matched,
    drugs = drugs,
    visits = visits,
    hosp = hosp
  )
}

cohort_names <- c("cohort_match_all", "cohort_match_inf_org", "cohort_match_inf", "cohort_match_org") %>% 
  gsub("cohort_match_", "", .)

```

## Sepses incidence un mirstība

```{r}
ggplot() +
  geom_bar(
    aes(x = gads, y = n, fill = sepsis), stat = "identity", data = sepsis_counts
  ) +
  geom_line(
    aes(x = gads, y = n, group=1), data = sepsis_hosp_mirusie_counts %>% filter(miris_hosp == "Y"), size = 1
  ) +
  theme_Publication() +
  scale_fill_Publication()


ggplot() +
  geom_bar(
    aes(x = gads, y = prop, fill = sepsis), stat = "identity", data = sepsis_counts
  ) +
  geom_line(
    aes(x = gads, y = prop, group=1), data = sepsis_hosp_mirusie_counts %>% filter(miris_hosp == "Y"), size = 1
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_Publication() +
  scale_fill_Publication()
```

```{r survival-plots}
survival_inputs <- list()

for (i in 1:4) {
  tmp <- matched_datasets[[i]] %>% 
    left_join(mirusie %>% rename(naves_datums = datums), by = "pid")

survival_inputs[[i]] <- tmp %>% 
  mutate(cens = ifelse(is.na(naves_datums) | naves_datums > as.Date("2020-12-31"), 0, 1)) %>% 
  # select(cohort, date1, naves_datums, cens) %>% 
  mutate(datums = ifelse(is.na(naves_datums) | naves_datums > as.Date("2020-12-31"), as.character(as.Date("2020-12-31")), as.character(naves_datums))) %>% 
  # mutate(format = gsub("[0-9]", "x", datums)) %>% 
  # count(format) %>% 
  mutate(datums = lubridate::ymd(datums)) %>% 
  mutate(time = as.integer(datums - date1)) %>% 
  select(cohort, time, cens) %>% 
  {.}
}

surv_plots <- list()

for (i in 1:4) {
  surv_plots[[i]] <- survfit2(Surv(time, cens) ~ cohort, data = survival_inputs[[i]]) %>% 
  ggsurvfit() +
  labs(
    x = "Days",
    y = "Overall survival probability"
  ) + 
  add_confidence_interval() +
  # add_risktable() +
  add_quantile(y_value = 0.9, color = "gray50", linewidth = 0.75) +
  add_quantile(y_value = 0.8, color = "blue", linewidth = 0.75) +
  scale_y_continuous(label = scales::percent,
                     breaks = seq(0, 1, by = 0.1),
                     expand = c(0.015, 0)) +
  scale_x_continuous(breaks = seq(0, 2500, by = 365),
                     expand = c(0.02, 0)) +
     ggtitle(paste0("Cohort: ", cohort_names[i]))
}

surv_plots[[1]]
surv_plots[[2]]
surv_plots[[3]]
surv_plots[[4]]
```


## HCRU salīdzināšana

```{r cohort_descr}
cohort_descr_list <- map(
  cohort_inputs,
  ~{
    x <- .
    x$cohort_matched %>% 
      select(-pid) %>% 
      tbl_summary(
        by = cohort,
        # type = all_continuous() ~ "continuous",
        statistic = all_continuous() ~ desc_stats
      ) %>% 
      bold_labels() %>% 
      # as_kable() %>% 
      {.}
  }
)

tbl_merge(cohort_descr_list, tab_spanner = paste0("Cohort: ", cohort_names))
```

```{r}
# plot(summary(m.out))
```

## Receptes

```{r drugs}
drug_aggr_list <- list()

for (i in 1:4) { # i <- 1
  tmp <- cohort_inputs[[i]]$drugs %>% 
    group_by(pid) %>% 
      summarise(
        skaits = n(),
        unique_atk = length(unique(atk_kods)),
        summa_valsts = sum(valsts_summa),
        summa_pac = sum(pacienta_lidzmaksajums),
        summa_kopa = summa_valsts + summa_pac
      )
  
  drug_aggr_list[[i]] <- cohort_inputs[[i]]$cohort_matched %>% 
    select(pid, cohort) %>% 
    left_join(tmp) %>% 
    mutate(skaits = replace_na(skaits, 0)) %>% 
    mutate(any = skaits > 0) %>% 
    select(pid, any, everything())
  
  print(i)
}

drug_descr_list <- map(
  drug_aggr_list,
  ~{
    x <- .
    x %>%
      select(-pid) %>% 
      tbl_summary(
        by = cohort,
        type = all_continuous() ~ "continuous",
        statistic = all_continuous() ~ desc_stats,
        missing = "no"
        ) %>%
      bold_labels()
  }
)

tbl_merge(drug_descr_list, tab_spanner = paste0("Cohort: ", cohort_names))
```

## Ambulatorie pakalpojumi

```{r ambul}
visits_aggr_list <- list()

for (i in 1:4){
  tmp <- cohort_inputs[[i]]$visits %>% 
    mutate(across(contains("summa"), ~as.numeric(.))) %>% 
    mutate(across(contains("iemaksa"), ~as.numeric(.))) %>% 
    group_by(pid, tips) %>% 
    summarise(
      skaits = n(),
      summa_epiz = sum(summa_epizodes, na.rm = TRUE),
      summa_manip = sum(summa_manipulacijas, na.rm = TRUE),
      summa_pac_iemaks_pac = sum(pacienta_iemaksa_no_pacienta, na.rm = TRUE),
      summa_pac_iemaks_valsts = sum(pacienta_iemaksa_no_valsts, na.rm = TRUE),
      summa_kopa = summa_epiz + summa_manip + summa_pac_iemaks_pac + summa_pac_iemaks_valsts
      ) %>% 
    ungroup()

  visits_aggr_list[[i]] <- crossing(cohort_inputs[[i]]$cohort_matched %>% select(pid, cohort), spec_codes %>% select(tips)) %>% 
    left_join(tmp) %>% 
    mutate(skaits = replace_na(skaits, 0)) %>% 
    mutate(any = skaits > 0) %>%
    select(pid, tips, any, everything())
  
  print(i)
}

tipi <- unique(visits_aggr_list[[1]]$tips)

visits_descr_list <- list()

for (i in 1:length(tipi)){ # i <- 1
  tips_i <- tipi[i]
  tmp_list <- map( 
    visits_aggr_list,
    ~{
      tmp <- .
      tmp <- tmp %>% 
        filter(tips == tips_i) %>% 
        select(-pid, -tips) %>%
        tbl_summary(
          by = cohort,
          type = list(contains("any") ~ "dichotomous", contains("skaits") ~ "continuous", contains("summa") ~ "continuous"),
          statistic = all_continuous() ~ desc_stats,
          missing = "no",
          digits = list(c(any, skaits) ~ 0, contains("summa") ~ 1)
          ) %>% 
        # add_p() %>% 
        # modify_caption(tips_i)
        {.}
    }
  )
  visits_descr_list[[i]] <- tbl_merge(tmp_list, tab_spanner = paste0("Cohort: ", cohort_names)) %>% 
    modify_caption(tips_i)
}


visits_descr_list[[1]]

visits_descr_list[[2]]

visits_descr_list[[3]]

visits_descr_list[[4]]

visits_descr_list[[5]]

visits_descr_list[[6]]
```

## Hospitalizācijas

```{r}
hosp_aggr_list <- list()

for (i in 1:4) { # i <- 1
  tmp <- cohort_inputs[[i]]$hosp %>% 
    # mutate(date1 = lubridate::ymd(date1)) %>% 
    # mutate(date2 = lubridate::ymd(date2)) %>% 
    # mutate(hosp_ilgums = as.integer(date2 - date1)) %>% 
    group_by(pid) %>% 
    summarise(
      skaits = n(),
      hosp_naktis = sum(hosp_ilgums)
    )
  
  hosp_aggr_list[[i]] <- cohort_inputs[[i]]$cohort_matched %>% 
    select(pid, cohort) %>% 
    left_join(tmp) %>% 
    mutate(skaits = replace_na(skaits, 0)) %>% 
    mutate(any = skaits > 0) %>% 
    select(pid, any, everything())
  
  print(i)
}

hosp_descr_list <- map(
  hosp_aggr_list,
  ~{
    x <- .
    x %>%
      select(-pid) %>% 
      tbl_summary(
        by = cohort,
        type = all_continuous() ~ "continuous",
        statistic = all_continuous() ~ desc_stats,
        missing = "no"
        ) %>%
      bold_labels()
  }
)

tbl_merge(hosp_descr_list, tab_spanner = paste0("Cohort: ", cohort_names))
```













