---
title: "Sepses trendi"
author: "Artis Luguzis"
date: 
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
rm(list = ls())
```

```{r libs}
library(tidyverse)
library(gtsummary)
```


```{r data}
# hospitalization level data
load(file = "data/04_analysis_data/sepsis_hosp_characteristics.RData")
load(file = "data/04_analysis_data/sepsis_patient_characteristics.RData")

# CSP population data
load(file = file.path("taskfiles", "derived", "csp_iedz.RData"))
load(file = file.path("taskfiles", "derived", "csp_iedz_vecums_gados.RData"))
```

```{r}
hosp_descr <- hosp_descr %>% 
  mutate(vecums_cat = cut(vecums, c(0, 40, 60, 80, Inf), right = FALSE, labels = c("18-39", "40-59", "60-79", "80+")))
```


```{r csp_processing}
# apstrādā datus
csp_iedz <- csp_iedz %>% 
  mutate(gads = as.numeric(gads)) %>% 
  rename(dzimums = dzim) %>% 
  mutate(dzimums = ifelse(dzimums == "Sievietes", "sieviete", "vīrietis"))

csp_iedz_gadi <- csp_iedz_gadi %>% 
  mutate(gads = as.numeric(gads)) %>%
  rename(dzimums = dzim) %>% 
  mutate(dzimums = ifelse(dzimums == "Sievietes", "sieviete", "vīrietis"))

# skaits pa gadiem
iedz_skaits_pa_gadiem <- csp_iedz %>%
  filter(between(as.integer(gads), 2015, 2020)) %>%
  group_by(gads) %>%
  summarise(skaits = sum(skaits)) %>%
  ungroup()

# skaits pa gadiem un vecuma / dzimuma grupās
iedz_skaits_pa_gadiem_grupas <- csp_iedz_gadi %>%
  filter(between(as.integer(gads), 2015, 2020)) %>%
  mutate(vecums_cat = cut(vec, c(0, 40, 60, 80, Inf), right = FALSE, labels = c("18-39", "40-59", "60-79", "80+"))) %>%
  group_by(gads, vecums_cat, dzimums) %>%
  summarise(skaits = sum(skaits)) %>% 
  group_by(gads) %>% 
  mutate(skaits_prop = skaits/sum(skaits)) %>% 
  ungroup()
```

```{r incidence}
# tīrā incidence
incidence <- hosp_descr %>% 
  group_by(gads) %>% 
  summarise(incidence = n()) %>% 
  left_join(iedz_skaits_pa_gadiem) %>% 
  mutate(incidence_100k = incidence/skaits * 10^5)

# vecuma-dzimuma koriģētā (i.e., pēc iedzīvotāju sastāva 2015. gadā)
incidence_by_groups <- hosp_descr %>% 
  group_by(gads, vecums_cat, dzimums) %>% 
  summarise(incidence = n()) %>%
  ungroup() %>% 
  left_join(iedz_skaits_pa_gadiem_grupas %>% select(-skaits_prop)) %>% 
  mutate(incidence_100k = incidence/skaits * 10^5)

# pievieno 2015. gada proporcijas
incidence_adj <- incidence_by_groups %>% 
  left_join(iedz_skaits_pa_gadiem_grupas %>% filter(gads == 2015), by = c("vecums_cat", "dzimums")) %>% 
  mutate(weighted_inc = skaits_prop * incidence_100k) %>% 
  select(-gads.y) %>% 
  rename(gads = gads.x) %>% 
  group_by(gads) %>% 
  summarise(incidence_100k_adj = round(sum(weighted_inc), 1))

incidence_total <- incidence %>% 
  left_join(incidence_adj) %>% 
  mutate(across(where(is.numeric), ~round(., 1)))
```

```{r cfr}
# case fatality
case_fatality <- hosp_descr %>% 
  group_by(gads) %>% 
  summarise(
    in_hosp_deaths = sum(nave),
    case_fatality = mean(nave)
  )

# vecuma-dzimuma koriģētā (i.e., pēc iedzīvotāju sastāva 2015. gadā)
case_fatality_by_groups <- hosp_descr %>%
  group_by(gads, vecums_cat, dzimums) %>%
  summarise(
    in_hosp_deaths = sum(nave),
    case_fatality = mean(nave)
  ) %>%
  ungroup()

# sepses gadījumu proporcija grupās pa gadiem
incidence_by_groups <- incidence_by_groups %>% 
  group_by(gads) %>% 
  mutate(prop = incidence / sum(incidence)) %>% 
  ungroup()

# pievieno 2014. gada proporcijas
case_fatality_adj <- case_fatality_by_groups %>%
  left_join(
    incidence_by_groups %>% filter(gads == 2015) %>% select(vecums_cat, dzimums, prop),
    by = c("vecums_cat", "dzimums")
  ) %>%
  mutate(weighted_cfr = prop * case_fatality) %>%
  group_by(gads) %>%
  summarise(case_fatality_adj = sum(weighted_cfr))

case_fatality_total <- case_fatality %>%
  left_join(case_fatality_adj) %>% 
  mutate(across(contains("case_"), ~round(. * 100, 1))) %>% 
  rename(
    `case_fatality_%` = case_fatality,
    `case_fatality_adj_%` = case_fatality_adj
  )
```

```{r mortality}
# mirstība uz 100k
mortality <- case_fatality %>% 
  select(gads, in_hosp_deaths) %>% 
  left_join(iedz_skaits_pa_gadiem) %>% 
  mutate(mortality_100k = in_hosp_deaths / skaits * 10^5) %>% 
  select(-skaits)

# mirstība uz 100k vecuma-dzimuma koriģētā
mortality_by_groups <- case_fatality_by_groups %>% 
  select(gads, vecums_cat, dzimums, in_hosp_deaths) %>% 
  left_join(iedz_skaits_pa_gadiem_grupas %>% select(-skaits_prop)) %>% 
  mutate(mortality_100k = in_hosp_deaths / skaits * 10^5)

# pievieno 2015. gada proporcijas
mortality_adj <- mortality_by_groups %>% 
  left_join(iedz_skaits_pa_gadiem_grupas %>% filter(gads == 2015), by = c("vecums_cat", "dzimums")) %>% 
  mutate(weighted_mort = skaits_prop * mortality_100k) %>% 
  select(-gads.y) %>% 
  rename(gads = gads.x) %>% 
  group_by(gads) %>% 
  summarise(mortality_100k_adj = sum(weighted_mort))

mortality_total <- mortality %>% 
  left_join(mortality_adj) %>% 
  mutate(across(where(is.numeric), ~round(., 1)))
```

```{r other-stats}
# pirmais sepses gadījums
pirma_sepse <- hosp_descr %>% 
  group_by(gads) %>% 
  summarise(
    incidence_1st_case = sum(pirma_sepse_gada)
  )

# hospitalizāciju skaits katram pacientam
sepsis_hosp_skaits <- patient_descr %>% 
  group_by(gads) %>% 
  summarise(
    median = median(n_sepsis_hosp),
    q1 = quantile(n_sepsis_hosp, 0.25),
    q3 = quantile(n_sepsis_hosp, 0.75)
  ) %>% 
  mutate(sepsis_hosp_skaits = paste0(median, " (", q1, ",", q3, ")")) %>% 
  select(gads, sepsis_hosp_skaits)

# pacienti ar atkārtotu hospitalizāciju
readmission <- patient_descr %>% 
  group_by(gads) %>% 
  summarise(`readmission_%` = round(mean(readmit_1g) * 100, 1))
```

# Incidences trendi

```{r}
incidence_trends <- incidence_total %>% 
  select(-skaits) %>% 
  left_join(pirma_sepse) %>%
  left_join(sepsis_hosp_skaits) %>% 
  left_join(case_fatality_total) %>% 
  left_join(mortality_total) %>% 
  left_join(readmission)

colnames_new <- incidence$gads

incidence_trends <- incidence_trends %>% 
  t() %>% 
  as.data.frame()

colnames(incidence_trends) <- colnames_new

incidence_trends <- incidence_trends[-1, ]

incidence_trends %>% knitr::kable()
```

# Sepses hospitalizāciju raksturojums

```{r hosp_summary}
out_tbl <- hosp_descr %>% 
  select(vecums, vecums_cat, everything()) %>% 
  select(-pirma_sepse_gada, -nave) %>% 
  tbl_summary(by = gads) %>% 
  bold_labels()

out_tbl
```

# Trendu virziens

```{r}
# apvieno abas tabuls
trend_df <- out_tbl %>% 
  as_tibble() %>% 
  janitor::clean_names()

trend_df <- bind_rows(
  incidence_trends %>% 
    rownames_to_column(var = "characteristic"),
  trend_df %>% 
    rename_with(~gsub("x|_.*", "", .), -characteristic)
) %>% 
  as_tibble()

# sagatavo datus regresijai
trend_df <- trend_df %>% 
  pivot_longer(-characteristic, names_to = "year", values_to = "value") %>% 
  drop_na(value) %>%
  mutate(value_num = gsub(" \\(.*", "", value)) %>% 
  mutate(value_num = gsub(",", "", value_num)) %>% 
  mutate(value_num = as.numeric(value_num)) %>%
  mutate(year = as.numeric(year)) %>% 
  select(characteristic, year, value_num) 
  
trend_df <- trend_df %>% 
  group_by(characteristic) %>% 
  nest() %>% 
  ungroup() %>% 
  mutate(fit = map(data, ~{lm(.$value_num ~ .$year, data = .)})) %>% 
  mutate(tidy_fit = map(fit, broom::tidy)) %>% 
  unnest(tidy_fit) %>% 
  filter(grepl("year", term)) %>% 
  select(characteristic, estimate, std.error, p.value) %>% 
  mutate(sig_trend = ifelse(p.value < 0.05, "Y", "N")) %>% 
  mutate(trend_direction = ifelse(estimate > 0, "Up", "Down")) %>% 
  mutate(trend_direction = ifelse(p.value > 0.05, "Uncertain", trend_direction)) %>% 
  mutate(across(is.numeric, ~sprintf("%.2f", .)))

trend_df %>% knitr::kable()
```


